kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: plugins/docker
  settings:
    repo: johnpeel/project1
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
- name: deploy
  image: peloton/drone-rancher
  settings:
    url: http://149.56.143.71:8080
    service: project1/project1
    docker_image: johnpeel/project1
    confirm: true
    timeout: 240
    start_first: false
    access_key:
      from_secret: rancher_access_key
    secret_key:
      from_secret: rancher_secret_key
